### ISSUE TITLE
Multiple laravel apps with SSO? How it works?

### ISSUE THREAD

**Issue by rasyidly** [sentrasoft/laravel-cas#1]
I have 2 (or more) laravel apps, different domain, and non HTTPS (just call ``authdomain.test`` and ``appdomain1.test``).. anyone know how to sign in ``appdomain1.test`` from ``authdomain.test``? Where should I place this package? for client? or server? How to make it all like google account (``authdomain``) with all services, like mail, drive, etc. (``appdomain1.test``)
Can anyone give me the simple example? thanks.. Im confused here for a week.. thanks..

**Comment by falestra** [comment]
Previously you had to have Apereo CAS Server, for example: https://login.domain.com. Then you can install this package in each client application (laravel apps).
