### ISSUE TITLE
How use laravel-CAS with Spatie laravel permission?

### ISSUE THREAD

**Issue by cod3r0k** [sentrasoft/laravel-cas#6]
Hi, How can I use laravel-CAS for login authentication and the I want to use any solution for my app permissions (such as spatie laravel-permission).

Could you help me...

**Comment by falestra** [comment]
Hello, this package applies to Laravel 5. *. I haven't had the chance to upgrade to the latest laravel version (upgrade as soon as possible).

Please note, after auth using cas, **you must store the cas user to local database**. Look at the Auth\CasController callback. After that, you can set the permissions with the **local User ID**.
